title: Quantum Chunks
description: Condensed Matter Physics, Quantum Computing, and Beyond
theme: just-the-docs

url: https://quantumchunks.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
